### PR TITLE
This should fix the Exception partially

### LINKED ISSUE #18: Fix exception handling
There are many unhandled exceptions in the codebase. Both the empty catch blocks and prints to `System.out`.
We want every exception handled and logged with [tinylog.Logger](https://tinylog.org/v2/).

For example, this regex: `^(?!\/\/|\/\*).*catch\s*(?:\([^)]*\))*\s*\{\s*(?:(?:\/\/|\/\*).*(\*\/)?\s*)*\}` will match every empty catch block (there are [24](https://i.imgur.com/I3KtHSh.png) of them).

Every `println()` in a non-empty catch block should be changed to `tinylog.Logger.err()`. (Related to #7) 
We should also catch specific exceptions instead of the more general ones. Catching `Throwable` should never be done, and catching `Exception` only if necessary (we can fix those in a separate issue/PR).

Edit: Added 7 commandments about exception handling:

1. Avoid empty catch blocks at all costs, if an empty catch block is intentional, make it clear with variable name and comment.
2. Catch specific exceptions instead of the more general ones. Catching `Throwable` should never be done, and catching `Exception` only if necessary. If there is more than one expected exception, catch them all individually instead of using one `Exception`.
3. Close every resource with _try-with-resources_.
4. Avoiding `null` checks that will hide bugs. Fail fast. `NullPointerException` is much more preferred than method failing to execute silently.
5. When there is new exception being thrown inside the catch block I prefer sending the original (causal) exception with the new one. More precisely, constructor `Exception(String message, Throwable cause)`.
6. Every exception should have a message describing what caused it.
7. Do not catch `NullPointerExample`
8. Fail even faster.

### PR DESCRIPTION
**Pull request by MaSven**
This will be hopefully the last big PR, to fix #18 .

### CODE REVIEW

File: src/main/java/BasisStatus/StatusIdle.java [hunk 1]
```diff
@@ -905,7 +905,7 @@ public void mouseMoved(MouseEvent e) {
 
             try {
                 vmObject.processAddElement(mainPath, circuitClass, frontClass, args);
-            } catch (Exception ex) {
+            } /* TODO why the exception here? */ catch (Exception ex) {
```
Comment (weisJ) [inline src/main/java/BasisStatus/StatusIdle.java:908]: Maybe it calls functions on elements. Because users can add own element implementations (I think) we need to make sure no exception is thrown. But this assumption probably has too much faith in whoever write this.

File: src/main/java/MyParser/Parser.java [hunk 2]
```diff
@@ -103,12 +103,12 @@ private boolean isIn(String ch, String set) {
      * private boolean isVariable(String val) { String ch; for(int i=0;i<val.length();i++) {
      * ch=val.substring(i,i+1); if (isIn(ch,ALPHA)==false) return false; } return true; }
      */
-
+    // TODO NumberUtils anyone?
```
Comment (weisJ) [inline src/main/java/MyParser/Parser.java:106]: Rather no NumberUtils but an api that is enough strongly typed to not check.

Comment (MaSven) [reply src/main/java/MyParser/Parser.java:106]: Something in that direction. I saw this code 5 times in a row. Where something is checked to be a number.

File: src/main/java/SimpleFileSystem/Main.java [hunk 3]
```diff
@@ -41,28 +42,24 @@ public Main() {}
     public static void main(String[] args) {
```
Comment (weisJ) [inline src/main/java/SimpleFileSystem/Main.java]: I thing this class can be removed complete it doesn't seem to be used anywhere.

File: src/main/java/VisualLogic/ElementPalette.java [hunk 4]
```diff
@@ -160,16 +152,20 @@ public String getEndung(String fileName) {
...
             while ((inputString = input.readLine()) != null) {
                 list.add(inputString);
             }
-            input.close();
-        } catch (Exception ex) {
-            // System.out.println("FEHLER : "+ex.getMessage());
+
+        } catch (FileNotFoundException e) {
+            org.tinylog.Logger.error(e);
+        } catch (IOException ioException) {
```
Comment (weisJ) [inline src/main/java/VisualLogic/ElementPalette.java]: Why not combine both exceptions into one path?

File: src/main/java/VisualLogic/StoreImageException.java [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+ * You should have received a copy of the GNU General Public License
+ * along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ *
+ */
+
+package VisualLogic;
+
+import java.io.IOException;
+
+public class StoreImageException extends IOException {
```
Comment (weisJ) [inline src/main/java/VisualLogic/StoreImageException.java]: Please move new exception classes into the `com.github.mylibrelab` package. (Same applies for the exceptions from the last PR).

File: src/main/java/VisualLogic/variables/VS1DInteger.java [hunk 6]
```diff
@@ -74,30 +77,32 @@ public void copyValueFrom(Object in) {
...
             dos.writeInt(value.length);
 
             for (int i = 0; i < value.length; i++) {
                 int val = value[i];
                 dos.writeInt(val);
             }
-        } catch (Exception ex) {
+        } catch (IOException ex) {
+            Logger.error(ex);
             System.err.println("Fehler in VS1DInteger.saveToStream() : " + ex.toString());
```
Comment (weisJ) [inline src/main/java/VisualLogic/variables/VS1DInteger.java]: `System.err` call should be removed.

File: src/main/java/VisualLogic/variables/VS1DString.java [hunk 7]
```diff
@@ -78,30 +81,32 @@ public void copyValueFrom(Object in) {
...
             int size = dis.readInt();
             value = new String[size];
 
             for (int i = 0; i < value.length; i++) {
                 value[i] = dis.readUTF();
             }
-        } catch (Exception ex) {
+        } catch (IOException ex) {
+            Logger.error(ex);
             System.err.println("Fehler in VS1DString.loadFromStream() : " + ex.toString());
```
Comment (weisJ) [inline src/main/java/VisualLogic/variables/VS1DString.java]: `System.err` call should be removed. It might be worth while to search for all uses of it. Won't comment on other occurrences.

File: src/main/java/VisualLogic/variables/VSImage.java [hunk 8]
```diff
@@ -116,13 +115,13 @@ public void loadFromStream(java.io.FileInputStream fis) {
                 if (image != null) {
                     image.flush();
                 }
-
+                // TODO ignored read here
```
Comment (weisJ) [inline src/main/java/VisualLogic/variables/VSImage.java]: Is this still Todo?

**Review by weisJ — CHANGES_REQUESTED** [review]

File: src/main/java/VisualLogic/variables/VSImage.java (hunk 8 above)
Comment (MaSven) [reply src/main/java/VisualLogic/variables/VSImage.java]: Yes just wanted to point it out. Sometimes reads from a stream are just ignored.

File: src/main/java/SimpleFileSystem/Main.java (hunk 3 above)
Comment (weisJ) [reply src/main/java/SimpleFileSystem/Main.java]: By thing I mean the whole class

File: src/main/java/VisualLogic/variables/VSImage.java (hunk 8 above)
Comment (weisJ) [reply src/main/java/VisualLogic/variables/VSImage.java]: Ok could you then clarify this in the comment a bit more? I though this was a Todo related to this PR.

File: src/main/java/VisualLogic/StoreImageException.java (hunk 5 above)
Comment (MaSven) [reply src/main/java/VisualLogic/StoreImageException.java]: Fixed here abb21125

File: src/main/java/VisualLogic/ElementPalette.java (hunk 4 above)
Comment (MaSven) [reply src/main/java/VisualLogic/ElementPalette.java]: addresed here 0aaf39a8

File: src/main/java/SimpleFileSystem/Main.java (hunk 3 above)
Comment (MaSven) [reply src/main/java/SimpleFileSystem/Main.java]: addresed here 067d2b19

File: src/main/java/VisualLogic/variables/VSImage.java (hunk 8 above)
Comment (MaSven) [reply src/main/java/VisualLogic/variables/VSImage.java]: Added comment here 1e91c2fd

File: src/main/java/VisualLogic/variables/VS1DInteger.java (hunk 6 above)
Comment (MaSven) [reply src/main/java/VisualLogic/variables/VS1DInteger.java]: Should we fix this in this PR too?

Comment (weisJ) [reply src/main/java/VisualLogic/variables/VS1DInteger.java]: Depending on how many occurrences we are speaking of this may be a separate PR.

**Comment by MaSven** [comment]
> Ah ok now I see what's happening here. `FileInputStream#read` populates the content of the byte array.

Yes you are right. It saves the bytes into the imageBytes array. I will delete the comment. Totally missed that

**Comment by marko-radosavljevic** [comment]
Please, before merging this, check other occurrences of bad exception handling with tools like SonarCloud, SpotBugs and PMD.

It would be nice if we could deal with all the bad handling in this PR, so we don't have to do these global exception fixes again. ^^
[Filtered exception bugs.](https://sonarcloud.io/project/issues?id=MyLibreLab_key254582&resolved=false&severities=BLOCKER&types=BUG)

**Comment by MaSven** [comment]
> Please, before merging this, check other occurrences of bad exception handling with tools like SonarCloud, SpotBugs and PMD.
> 
> I would be nice if we could deal with all bad handling in this PR, so we don't have to do these global exception fixes again. ^^
> [Filtered exception bugs.](https://sonarcloud.io/project/issues?id=MyLibreLab_key254582&resolved=false&severities=BLOCKER&types=BUG)

We have another big PR. If I change too much here the other PR will get problems merging them. What does @weisJ think?

File: src/main/java/VisualLogic/variables/VS1DInteger.java (hunk 6 above)
Comment (MaSven) [reply src/main/java/VisualLogic/variables/VS1DInteger.java]:
```bash
❯ rg --count "System.err.println" src/ | cut -d':' -f 2 | count
16
```

**Comment by weisJ** [comment]
From the legacy files my PR actually only touches `DialogLicence` and `FrameMain` and basically all changes are deletions . Everything else is self contained and shouldn't make any problems with the changes here.

**Comment by MaSven** [comment]
Ok i will check sonar if there is anything left for Exceptionhandling.

File: src/main/java/VisualLogic/variables/VS1DInteger.java (hunk 6 above)
Comment (weisJ) [reply src/main/java/VisualLogic/variables/VS1DInteger.java]: I thinks that is manageable to include in here.

Comment (MaSven) [reply src/main/java/VisualLogic/variables/VS1DInteger.java]: alright

**Comment by MaSven** [comment]
So i think i now have everything. Let me know if there is anything left.

File: src/main/java/de/myopenlab/update/UnzipFiles.java [hunk 9]
```diff
@@ -48,29 +48,31 @@ public void unzip(String zipFilePath, String destDirectory) throws IOException {
...
 
-            String filePath = destDirectory + File.separator + entry.getName();
-            if (!entry.isDirectory()) {
+            ZipEntry entry = zipIn.getNextEntry();
+            // iterates over entries in the zip file
+            while (entry != null) {
 
-                String tmp = new File(filePath).getParent();
-                new File(tmp).mkdirs();
+                String filePath = destDirectory + File.separator + entry.getName();
```
Comment (MaSven) [inline src/main/java/de/myopenlab/update/UnzipFiles.java:57]: Yes we write here Arbitrary. But that should not matter right now.

**Review by marko-radosavljevic — APPROVED** [review]
